### ISSUE TITLE
Pi-top/helios questions 

### ISSUE THREAD

**Issue by LWP2262** [SolarCarChallenge/pi-top#2]
The helios board says to update the firmware, how do I do that? I have tried uploading the .ino file, but I can't figure out what board it is. 

Also every time I try to open main.py I get an error saying "No such file or directory: COM6"

Thanks for all of the helpful stuff on here!!

**Comment by gte718p** [comment]
Two excellent issues.

Despite what the board says, it actually does have the current firmware on it.

For the COM 6 issue, I believe you have an old version of the software.  That was a poor example of coding on my part.  COM 6 is where is was connecting on my windows box.  
The line ser=serial.Serial('COM 6')  needs to be changed to  ser=serial.Serial('/dev/ttyS0', 57600)
