### ISSUE TITLE
Keeping Aux System and Main System Separate

### ISSUE THREAD

**Issue by MattAlbritton** [SolarCarChallenge/pi-top#7]
I have the boards and pi-top up and running well. However, I am encountering a problem when trying to hook up the main power system to the ADC in order to read my main voltage and current. On the solar car boards, there are only one input for each ADCs. Do all of the ADCS have the same ground? If so, this would mean our aux system and main system would be grounded together. How can we read both aux voltage and main voltage on the ADCs with different grounds to keep them separate? Thanks in advance.

**Comment by gte718p** [comment]
Matt,

For they system to work both the Aux and Main grounds have to be tied together.  They also need to be tied to the power ground of the board.  While this is would normally be illegal under the rules, we are granting an exception for telemetry.  Obviously you will fail the ground test at scrutineering.  You should be asked if you have the pi-top installed and then be ask to lift the ground leads from the board to prove that is the only common ground.  Assuming you pass, with the lead lifted you are good to go.

A couple of safety notes.  In generally tying the high and low voltage systems together creates a risk.  That can be mitigated in several ways.  While we are not requiring it, I would highly recommend running fuses on the ground leads.  These are not current carrying wires so they should be of extremely small size (high gauge).

I will also point out the pi-top is a high voltage system and should be treated as such.

If for some reason this becomes an issue at srutineering, come find William or myself (Jarrett)
